import React from "react";
import { extractCss } from "goober";

/**
 * @deprecated Stitches compatibility shim — will be removed.
 */
export const easyblocksStitchesInstances: any[] = [];

/**
 * Returns accumulated CSS text **and flushes** goober's internal buffer.
 *
 * NOTE: goober's `extractCss()` always resets the buffer after reading.
 * There is no way to read without flushing. This means every call returns
 * only the CSS that was generated since the previous call.
 *
 * @deprecated Use {@link easyblocksGetCssTextAndFlush} for clarity.
 */
export function easyblocksGetCssText() {
  return extractCss();
}

/**
 * Returns accumulated CSS text and flushes the buffer so that subsequent
 * calls only return newly-added styles. This prevents the same CSS block
 * from being emitted multiple times during SSR streaming.
 *
 * goober's `extractCss()` automatically resets the buffer.
 */
export function easyblocksGetCssTextAndFlush() {
  return extractCss();
}

/**
 * @deprecated Use `easyblocksGetStyleTagAndFlush` instead for proper deduplication.
 */
export function easyblocksGetStyleTag() {
  return easyblocksGetStyleTagAndFlush();
}

/**
 * Resets SSR state. Call this at the beginning of each SSR request to prevent
 * CSS generated by one request from leaking into another via goober's shared
 * module-level buffer.
 */
export function easyblocksResetSsrState() {
  // Drain any leftover CSS from a previous request so it doesn't leak.
  extractCss();
}

/**
 * Returns a `<style>` tag with the accumulated CSS and flushes the buffer.
 * Safe to call from `useServerInsertedHTML` — subsequent calls within the
 * same render cycle return only the delta (newly added styles).
 *
 * Returns `null` when there is no new CSS to inject.
 *
 * Always uses `id="_goober"` — goober's own style-tag id.  On the client,
 * goober's `getSheet()` looks up `window._goober` and reuses the
 * SSR-emitted element.  Its internal `update()` function checks
 * `sheet.data.indexOf(css) === -1` before appending, so any rule already
 * present in the SSR tag is silently skipped during hydration.
 */
export function easyblocksGetStyleTagAndFlush() {
  const css = easyblocksGetCssTextAndFlush();

  if (!css) {
    return null;
  }

  return <style id="_goober" dangerouslySetInnerHTML={{ __html: css }} />;
}
