import React from "react";
import { extractCss } from "goober";

/**
 * @deprecated Stitches compatibility shim — will be removed.
 */
export const easyblocksStitchesInstances: any[] = [];

/**
 * Returns accumulated CSS text **and flushes** goober's internal buffer.
 *
 * NOTE: goober's `extractCss()` always resets the buffer after reading.
 * There is no way to read without flushing. This means every call returns
 * only the CSS that was generated since the previous call.
 *
 * @deprecated Use {@link easyblocksGetCssTextAndFlush} for clarity.
 */
export function easyblocksGetCssText() {
  return extractCss();
}

/**
 * Returns accumulated CSS text and flushes the buffer so that subsequent
 * calls only return newly-added styles. This prevents the same CSS block
 * from being emitted multiple times during SSR streaming.
 *
 * goober's `extractCss()` automatically resets the buffer.
 */
export function easyblocksGetCssTextAndFlush() {
  return extractCss();
}

/**
 * @deprecated Use `easyblocksGetStyleTagAndFlush` instead for proper deduplication.
 */
export function easyblocksGetStyleTag() {
  return easyblocksGetStyleTagAndFlush();
}

let _flushCounter = 0;

/**
 * Resets the internal flush counter. Call this at the beginning of each SSR
 * request to prevent the counter from growing unboundedly across requests in
 * a long-lived server process, and to prevent CSS generated by one request
 * from leaking into another via goober's shared module-level buffer.
 */
export function easyblocksResetSsrState() {
  _flushCounter = 0;
  // Drain any leftover CSS from a previous request so it doesn't leak.
  extractCss();
}

/**
 * Returns a `<style>` tag with the accumulated CSS and flushes the buffer.
 * Safe to call from `useServerInsertedHTML` — subsequent calls within the
 * same render cycle return only the delta (newly added styles).
 *
 * Returns `null` when there is no new CSS to inject.
 */
export function easyblocksGetStyleTagAndFlush() {
  const css = easyblocksGetCssTextAndFlush();

  if (!css) {
    return null;
  }

  // Use a unique id per flush so React doesn't deduplicate the elements
  const id = `easyblocks-css${_flushCounter > 0 ? `-${_flushCounter}` : ""}`;
  _flushCounter++;

  return <style id={id} dangerouslySetInnerHTML={{ __html: css }} />;
}
